---
  .travis.yml:
    hc_secure: "CyI7X1ChFNoDKUjxWAJqK1fR9m3scK3aK8xMe9mlherTxlbhoGUpzryw174bs43YkpsYp0tPwMYNztlDxBPjVIAzrqv9kDr41FsPQHhrZ3YaD5pu01egMOEyOAxpFHCPOB7ZXgYnP1wu1aen2tnpoPIQtaQ5BRbGmYRjBfEmswU="

