name 'evenup-riakdev'
version '1.3.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
project_page 'https://github.com/evenup/evenup-riakdev'
summary 'Installs a Riak 4 node development cluster'
description 'Installs a Riak 4 node development cluster on a single host'
#dependency 'evenup/backups', '>= 1.0.0'
dependency 'sensu/sensu', '>= 0.5.0'

